registry:
  rarities:
    epic:
      name: '<dark_purple>EPIC'
      chance: 3

  guns:
    ak-47:
      name: 'AK-47'
      rarity: 'epic'
      shoot-cooldown: 200
      damage: 3
      velocity: 40
      ammo: '9mm'

  ammo:
    9mm:
      name: '9mm'
      rarity: 'epic'